### ISSUE TITLE
Is there a public testnet yet?

### ISSUE THREAD

**Issue by bitjson** [bitcoin-hivemind/hivemind#20]
I'd be very happy to run a node.

**Comment by CryptAxe** [comment]
Hello I'm working on getting a testnet running for everyone right now! Should be up and running very soon I'll let you know when you can start testing.

**Comment by bitjson** [comment]
Awesome. Has anyone taken a look at a DNS seed for Hivemind (like [bitcoin-seeder](https://github.com/sipa/bitcoin-seeder))?

**Comment by CryptAxe** [comment]
Yes I've added our seed node to the testnet I'm working on. I'm in the process of getting everything ready for a pull request but there will be seed nodes once it's ready :) I think we are going to have to setup up some more in the near future as well though, so I'll let you know once we are ready to get some more running.

**Comment by CryptAxe** [comment]
Hey I have to finish a few things before the testnet can be created, and I've created https://github.com/bitcoin-hivemind/testnet-canonical which is where all testnet stuff is going.

**Comment by CryptAxe** [comment]
Renaming this to fit the hivemind roadmap, and make it clear that it is a high priority issue

**Comment by CryptAxe** [comment]
I think we can probably close this issue now @bitjson and @psztorc everything on https://github.com/bitcoin-hivemind/testnet-canonical is ready to go.

**Comment by bitjson** [comment]
Agreed. Great work!
