### ISSUE TITLE
way to make hivemind 1000s of times more efficient.

### ISSUE THREAD

**Issue by zack-bitcoin** [bitcoin-hivemind/hivemind#80]
https://github.com/BumblebeeBat/FlyingFox/blob/master/docs/cheaper_alternative_to_reputation_truthcoin.md

**Comment by psztorc** [comment]
> Keeping money in reputation is expensive by the interest rate. If your money is invested in rep, you can't also invest it elsewhere.

This is correct, but what's the point? These two sentences are true for all investments / projects to ever exist.

Zack, your technical writing would probably be easier to understand, if you used the "scientific organization". In Bitcoin, BIPs typically run something like: Abstract, Motivation, Problem, Definitions, Solution, Code, Example, Notes, Attribution, Copyright.

As it stands, I can't even tell what problem you are trying to solve.

For example, you say:

> This paper improves on Bitcoin Hivemind's protocol by heavily reducing the amount of money that needs to be locked up.

But that is not necessarily an improvement. I could rewrite your sentence as "this paper damages Bitcoin Hivemind by making it cheaper to execute a 51% REP attack".

**Comment by zack-bitcoin** [comment]
The problem I am trying to solve is making truthcoin more affordable to operate.

The point of those 2 sentences is to quantify how much it costs truthcoin to operate.

As you can see from the example, $30,000 are used as a security deposit to secure $10,000 of gambling, so the protocol I suggest is cryptoeconomically secure against 51% rep attacks. 

For an outcome to be valid at least 2/3rds of reporters need to report to it. If 2 different outcomes both have 2/3rds, then at least 1/3rd of reporters double-report.
That is why the security deposit is 3x bigger than what it secures.

**Comment by zack-bitcoin** [comment]
My mistake, it doesn't work.
