### ISSUE TITLE
Problem with how channels are designed

### ISSUE THREAD

**Issue by zack-bitcoin** [bitcoin-hivemind/hivemind#98]
It would be nice if we could do trading of shares inside of a channel.
The problem is that we only want to trade shares at the current market price.
We want our traders to be secure against front-running, and free options.

The only way to achieve these goals is to move the market mechanism off-chain into the channels.

I implemented some channels for my blockchain that are turing complete.
I wrote an off-chain market for these channels.

I think it would be easier to use the turing complete channels I invented, rather than trying to upgrade bitcoin channels to the point where they can support markets.

**Comment by psztorc** [comment]
Have you seen this: http://bitcoinhivemind.com/blog/lightning-network/

**Comment by zack-bitcoin** [comment]
Yes I have.
I was the first to comment on it.
I reviewed it again just now.

You put effort into requiring that off-chain traders pay the same trading fee to the oracle.

This article does not address the concerns I raised.

**Comment by psztorc** [comment]
It addresses "It would be nice if we could do trading of shares inside of a channel."

What other concerns do you have?

**Comment by zack-bitcoin** [comment]
The ability to trade at the wrong price isn't valuable.
No one wants to participate in a market where they get scammed out of 10% of their money every time.

Off-chain trading is only valuable if it is done in an off-chain market. That way traders can trade at the current market price.
Otherwise every trade is a free option, and every trade will be front-run every time.

I have already implemented an off-chain market, and I can help you to achieve this goal.

**Comment by psztorc** [comment]
The LN hubs are like exchanges (such as BATS, NADEX, NYSE, etc) and also like brokerage firms (Interactive Brokers, e-Trade, etc). Their users can buy or sell whatever they like at any price.

**Comment by zack-bitcoin** [comment]
The LN hubs in my blockchain are like exchange too.
They match trades trustlessly, at the current market price.
Every trader who trades the same asset during the same time period gets the same price.
So you may end up trading at a more favorable price than you were willing to pay.

It seems like the hubs in the network you are building have an incentive to simultaneously match different customers trading the same asset at different prices. That way the hub can take hidden fees from the customers. The hub would charge the customer the highest price that the customer is willing to pay.

**Comment by psztorc** [comment]
No, the hubs are very competitive. They will charge the user the lowest price possible.

Sorry that you misunderstood that.

**Comment by zack-bitcoin** [comment]
Yes, the LN nodes are in competition. 
That is an important point I had not considered properly.
Thank you for the help.
